import Foundation

enum Prefecture: String, CaseIterable, Identifiable {
    case hokkaido = "北海道"
    case aomori = "青森"
    case iwate = "岩手"
    case miyagi = "宮城"
    case akita = "秋田"
    case yamagata = "山形"
    case fukushima = "福島"
    case ibaraki = "茨城"
    case tochigi = "栃木"
    case gunma = "群馬"
    case saitama = "埼玉"
    case chiba = "千葉"
    case tokyo = "東京"
    case kanagawa = "神奈川"
    case niigata = "新潟"
    case toyama = "富山"
    case ishikawa = "石川"
    case fukui = "福井"
    case yamanashi = "山梨"
    case nagano = "長野"
    case gifu = "岐阜"
    case shizuoka = "静岡"
    case aichi = "愛知"
    case mie = "三重"
    case shiga = "滋賀"
    case kyoto = "京都"
    case osaka = "大阪"
    case hyogo = "兵庫"
    case nara = "奈良"
    case wakayama = "和歌山"
    case tottori = "鳥取"
    case shimane = "島根"
    case okayama = "岡山"
    case hiroshima = "広島"
    case yamaguchi = "山口"
    case tokushima = "徳島"
    case kagawa = "香川"
    case ehime = "愛媛"
    case kochi = "高知"
    case fukuoka = "福岡"
    case saga = "佐賀"
    case nagasaki = "長崎"
    case kumamoto = "熊本"
    case oita = "大分"
    case miyazaki = "宮崎"
    case kagoshima = "鹿児島"
    case okinawa = "沖縄"
    
    var id: String { rawValue }
    var displayName: String { rawValue }
}
